var my_apple;
my_apple = "strawberry";
var my_name = "akshay palase";
console.log(my_apple);
console.log(my_name);
console.log(`========practice below=========`);
console.log(`====assignment1====`);
console.log(`Akshay arun palase`);
console.log(`Playing cricket,vollyball,listening to music`);
console.log(`self movtivated,ambitious,polite`);
console.log(`helps everyone,focused at one work at a time,friendly`);
console.log(30+50);
console.log(49*479);
console.log(``);
console.log(``);
console.log(``);
console.log(`====assignment2====`);
var myFullName;
myFullName="Akshay palase";
console.log(myFullName);
myFullName="Akshay Arun Palase";
console.log(myFullName);
var myLove="I love only JS";
console.log(myLove);
var firstName="Akshay",lastName="palase",age=25,address="thane",pin_code=401107,gender="male",married="no";
console.log(firstName,lastName,age,address,pin_code,gender,married);